//
//  CorePlugin.xrplugin.h
//  MacDemo
//
//  Created by szzc on 2016/11/25.
//  Copyright © 2016年 szzc. All rights reserved.
//

#ifndef CorePlugin_xrplugin_h
#define CorePlugin_xrplugin_h
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/CorePlugin.xrplugin/Contents/MacOS/CorePlugin
// UUID: 8D83A206-DCBC-37C0-B0C2-64CB1FA26DFC
//
//                           Arch: x86_64
//                 Source version: 61529.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.12.0
//

//
// This file does not contain any Objective-C runtime information.

#endif /* CorePlugin_xrplugin_h */
