//
//  DataElementsPlugin.xrplugin.h
//  MacDemo
//
//  Created by szzc on 2016/11/25.
//  Copyright © 2016年 szzc. All rights reserved.
//

#ifndef DataElementsPlugin_xrplugin_h
#define DataElementsPlugin_xrplugin_h
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/DataElementsPlugin.xrplugin/Contents/MacOS/DataElementsPlugin
// UUID: 157BA942-C8E1-3650-BD51-60AC3EF819CD
//
//                           Arch: x86_64
//                 Source version: 61529.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.12.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @loader_path/../../../../Frameworks
//                               = /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks
//                       Run path: @loader_path/../../../../../../../../SharedFrameworks
//                               = /Applications/Xcode.app/SharedFrameworks
//

@protocol CommonSymbol <NSCoding, NSObject>
- (NSString *)libraryPath;
- (NSString *)libraryName;
- (NSString *)symbolName;
- (int)pid;
- (unsigned long long)lineNumber;
- (NSString *)sourcePath;
- (unsigned long long)address;

@optional
- (PFTSymbolData *)resolvedSymbol;
@end

@protocol NSCoding
- (id)initWithCoder:(NSCoder *)arg1;
- (void)encodeWithCoder:(NSCoder *)arg1;
@end

@protocol NSControlTextEditingDelegate <NSObject>

@optional
- (NSArray *)control:(NSControl *)arg1 textView:(NSTextView *)arg2 completions:(NSArray *)arg3 forPartialWordRange:(struct _NSRange)arg4 indexOfSelectedItem:(long long *)arg5;
- (BOOL)control:(NSControl *)arg1 textView:(NSTextView *)arg2 doCommandBySelector:(SEL)arg3;
- (BOOL)control:(NSControl *)arg1 isValidObject:(id)arg2;
- (void)control:(NSControl *)arg1 didFailToValidatePartialString:(NSString *)arg2 errorDescription:(NSString *)arg3;
- (BOOL)control:(NSControl *)arg1 didFailToFormatString:(NSString *)arg2 errorDescription:(NSString *)arg3;
- (BOOL)control:(NSControl *)arg1 textShouldEndEditing:(NSText *)arg2;
- (BOOL)control:(NSControl *)arg1 textShouldBeginEditing:(NSText *)arg2;
@end

@protocol NSMenuDelegate <NSObject>

@optional
- (struct CGRect)confinementRectForMenu:(NSMenu *)arg1 onScreen:(NSScreen *)arg2;
- (void)menu:(NSMenu *)arg1 willHighlightItem:(NSMenuItem *)arg2;
- (void)menuDidClose:(NSMenu *)arg1;
- (void)menuWillOpen:(NSMenu *)arg1;
- (BOOL)menuHasKeyEquivalent:(NSMenu *)arg1 forEvent:(NSEvent *)arg2 target:(id *)arg3 action:(SEL *)arg4;
- (BOOL)menu:(NSMenu *)arg1 updateItem:(NSMenuItem *)arg2 atIndex:(long long)arg3 shouldCancel:(BOOL)arg4;
- (long long)numberOfItemsInMenu:(NSMenu *)arg1;
- (void)menuNeedsUpdate:(NSMenu *)arg1;
@end

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(Protocol *)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (BOOL)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol NSTableViewDataSource <NSObject>

@optional
- (NSArray *)tableView:(NSTableView *)arg1 namesOfPromisedFilesDroppedAtDestination:(NSURL *)arg2 forDraggedRowsWithIndexes:(NSIndexSet *)arg3;
- (BOOL)tableView:(NSTableView *)arg1 acceptDrop:(id <NSDraggingInfo>)arg2 row:(long long)arg3 dropOperation:(unsigned long long)arg4;
- (unsigned long long)tableView:(NSTableView *)arg1 validateDrop:(id <NSDraggingInfo>)arg2 proposedRow:(long long)arg3 proposedDropOperation:(unsigned long long)arg4;
- (BOOL)tableView:(NSTableView *)arg1 writeRowsWithIndexes:(NSIndexSet *)arg2 toPasteboard:(NSPasteboard *)arg3;
- (void)tableView:(NSTableView *)arg1 updateDraggingItemsForDrag:(id <NSDraggingInfo>)arg2;
- (void)tableView:(NSTableView *)arg1 draggingSession:(NSDraggingSession *)arg2 endedAtPoint:(struct CGPoint)arg3 operation:(unsigned long long)arg4;
- (void)tableView:(NSTableView *)arg1 draggingSession:(NSDraggingSession *)arg2 willBeginAtPoint:(struct CGPoint)arg3 forRowIndexes:(NSIndexSet *)arg4;
- (id <NSPasteboardWriting>)tableView:(NSTableView *)arg1 pasteboardWriterForRow:(long long)arg2;
- (void)tableView:(NSTableView *)arg1 sortDescriptorsDidChange:(NSArray *)arg2;
- (void)tableView:(NSTableView *)arg1 setObjectValue:(id)arg2 forTableColumn:(NSTableColumn *)arg3 row:(long long)arg4;
- (id)tableView:(NSTableView *)arg1 objectValueForTableColumn:(NSTableColumn *)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(NSTableView *)arg1;
@end

@protocol NSTableViewDelegate <NSControlTextEditingDelegate>

@optional
- (void)tableViewSelectionIsChanging:(NSNotification *)arg1;
- (void)tableViewColumnDidResize:(NSNotification *)arg1;
- (void)tableViewColumnDidMove:(NSNotification *)arg1;
- (void)tableViewSelectionDidChange:(NSNotification *)arg1;
- (NSArray *)tableView:(NSTableView *)arg1 rowActionsForRow:(long long)arg2 edge:(long long)arg3;
- (BOOL)tableView:(NSTableView *)arg1 shouldReorderColumn:(long long)arg2 toColumn:(long long)arg3;
- (double)tableView:(NSTableView *)arg1 sizeToFitWidthOfColumn:(long long)arg2;
- (BOOL)tableView:(NSTableView *)arg1 isGroupRow:(long long)arg2;
- (BOOL)tableView:(NSTableView *)arg1 shouldTypeSelectForEvent:(NSEvent *)arg2 withCurrentSearchString:(NSString *)arg3;
- (long long)tableView:(NSTableView *)arg1 nextTypeSelectMatchFromRow:(long long)arg2 toRow:(long long)arg3 forString:(NSString *)arg4;
- (NSString *)tableView:(NSTableView *)arg1 typeSelectStringForTableColumn:(NSTableColumn *)arg2 row:(long long)arg3;
- (double)tableView:(NSTableView *)arg1 heightOfRow:(long long)arg2;
- (void)tableView:(NSTableView *)arg1 didDragTableColumn:(NSTableColumn *)arg2;
- (void)tableView:(NSTableView *)arg1 didClickTableColumn:(NSTableColumn *)arg2;
- (void)tableView:(NSTableView *)arg1 mouseDownInHeaderOfTableColumn:(NSTableColumn *)arg2;
- (BOOL)tableView:(NSTableView *)arg1 shouldSelectTableColumn:(NSTableColumn *)arg2;
- (NSIndexSet *)tableView:(NSTableView *)arg1 selectionIndexesForProposedSelection:(NSIndexSet *)arg2;
- (BOOL)tableView:(NSTableView *)arg1 shouldSelectRow:(long long)arg2;
- (BOOL)selectionShouldChangeInTableView:(NSTableView *)arg1;
- (NSCell *)tableView:(NSTableView *)arg1 dataCellForTableColumn:(NSTableColumn *)arg2 row:(long long)arg3;
- (BOOL)tableView:(NSTableView *)arg1 shouldTrackCell:(NSCell *)arg2 forTableColumn:(NSTableColumn *)arg3 row:(long long)arg4;
- (BOOL)tableView:(NSTableView *)arg1 shouldShowCellExpansionForTableColumn:(NSTableColumn *)arg2 row:(long long)arg3;
- (NSString *)tableView:(NSTableView *)arg1 toolTipForCell:(NSCell *)arg2 rect:(struct CGRect *)arg3 tableColumn:(NSTableColumn *)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;
- (BOOL)tableView:(NSTableView *)arg1 shouldEditTableColumn:(NSTableColumn *)arg2 row:(long long)arg3;
- (void)tableView:(NSTableView *)arg1 willDisplayCell:(id)arg2 forTableColumn:(NSTableColumn *)arg3 row:(long long)arg4;
- (void)tableView:(NSTableView *)arg1 didRemoveRowView:(NSTableRowView *)arg2 forRow:(long long)arg3;
- (void)tableView:(NSTableView *)arg1 didAddRowView:(NSTableRowView *)arg2 forRow:(long long)arg3;
- (NSTableRowView *)tableView:(NSTableView *)arg1 rowViewForRow:(long long)arg2;
- (NSView *)tableView:(NSTableView *)arg1 viewForTableColumn:(NSTableColumn *)arg2 row:(long long)arg3;
@end

@protocol NSTextDelegate <NSObject>

@optional
- (void)textDidChange:(NSNotification *)arg1;
- (void)textDidEndEditing:(NSNotification *)arg1;
- (void)textDidBeginEditing:(NSNotification *)arg1;
- (BOOL)textShouldEndEditing:(NSText *)arg1;
- (BOOL)textShouldBeginEditing:(NSText *)arg1;
@end

@protocol NSTextFieldDelegate <NSControlTextEditingDelegate>

@optional
- (BOOL)textField:(NSTextField *)arg1 textView:(NSTextView *)arg2 shouldSelectCandidateAtIndex:(unsigned long long)arg3;
- (NSArray *)textField:(NSTextField *)arg1 textView:(NSTextView *)arg2 candidates:(NSArray *)arg3 forSelectedRange:(struct _NSRange)arg4;
- (NSArray *)textField:(NSTextField *)arg1 textView:(NSTextView *)arg2 candidatesForSelectedRange:(struct _NSRange)arg3;
@end

@protocol NSTextViewDelegate <NSTextDelegate>

@optional
- (void)textView:(NSTextView *)arg1 draggedCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3 event:(NSEvent *)arg4;
- (void)textView:(NSTextView *)arg1 doubleClickedOnCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3;
- (void)textView:(NSTextView *)arg1 clickedOnCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3;
- (BOOL)textView:(NSTextView *)arg1 clickedOnLink:(id)arg2;
- (BOOL)textView:(NSTextView *)arg1 shouldSelectCandidateAtIndex:(unsigned long long)arg2;
- (NSArray *)textView:(NSTextView *)arg1 candidates:(NSArray *)arg2 forSelectedRange:(struct _NSRange)arg3;
- (NSArray *)textView:(NSTextView *)arg1 candidatesForSelectedRange:(struct _NSRange)arg2;
- (NSArray *)textView:(NSTextView *)arg1 shouldUpdateTouchBarItemIdentifiers:(NSArray *)arg2;
- (NSUndoManager *)undoManagerForTextView:(NSTextView *)arg1;
- (NSSharingServicePicker *)textView:(NSTextView *)arg1 willShowSharingServicePicker:(NSSharingServicePicker *)arg2 forItems:(NSArray *)arg3;
- (NSURL *)textView:(NSTextView *)arg1 URLForContentsOfTextAttachment:(NSTextAttachment *)arg2 atIndex:(unsigned long long)arg3;
- (NSArray *)textView:(NSTextView *)arg1 didCheckTextInRange:(struct _NSRange)arg2 types:(unsigned long long)arg3 options:(NSDictionary *)arg4 results:(NSArray *)arg5 orthography:(NSOrthography *)arg6 wordCount:(long long)arg7;
- (NSDictionary *)textView:(NSTextView *)arg1 willCheckTextInRange:(struct _NSRange)arg2 options:(NSDictionary *)arg3 types:(unsigned long long *)arg4;
- (NSMenu *)textView:(NSTextView *)arg1 menu:(NSMenu *)arg2 forEvent:(NSEvent *)arg3 atIndex:(unsigned long long)arg4;
- (long long)textView:(NSTextView *)arg1 shouldSetSpellingState:(long long)arg2 range:(struct _NSRange)arg3;
- (BOOL)textView:(NSTextView *)arg1 doCommandBySelector:(SEL)arg2;
- (BOOL)textView:(NSTextView *)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(NSString *)arg3;
- (NSArray *)textView:(NSTextView *)arg1 completions:(NSArray *)arg2 forPartialWordRange:(struct _NSRange)arg3 indexOfSelectedItem:(long long *)arg4;
- (NSString *)textView:(NSTextView *)arg1 willDisplayToolTip:(NSString *)arg2 forCharacterAtIndex:(unsigned long long)arg3;
- (void)textViewDidChangeTypingAttributes:(NSNotification *)arg1;
- (void)textViewDidChangeSelection:(NSNotification *)arg1;
- (NSDictionary *)textView:(NSTextView *)arg1 shouldChangeTypingAttributes:(NSDictionary *)arg2 toAttributes:(NSDictionary *)arg3;
- (BOOL)textView:(NSTextView *)arg1 shouldChangeTextInRanges:(NSArray *)arg2 replacementStrings:(NSArray *)arg3;
- (NSArray *)textView:(NSTextView *)arg1 willChangeSelectionFromCharacterRanges:(NSArray *)arg2 toCharacterRanges:(NSArray *)arg3;
- (struct _NSRange)textView:(NSTextView *)arg1 willChangeSelectionFromCharacterRange:(struct _NSRange)arg2 toCharacterRange:(struct _NSRange)arg3;
- (BOOL)textView:(NSTextView *)arg1 writeCell:(id <NSTextAttachmentCell>)arg2 atIndex:(unsigned long long)arg3 toPasteboard:(NSPasteboard *)arg4 type:(NSString *)arg5;
- (NSArray *)textView:(NSTextView *)arg1 writablePasteboardTypesForCell:(id <NSTextAttachmentCell>)arg2 atIndex:(unsigned long long)arg3;
- (void)textView:(NSTextView *)arg1 draggedCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3 event:(NSEvent *)arg4 atIndex:(unsigned long long)arg5;
- (void)textView:(NSTextView *)arg1 doubleClickedOnCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3 atIndex:(unsigned long long)arg4;
- (void)textView:(NSTextView *)arg1 clickedOnCell:(id <NSTextAttachmentCell>)arg2 inRect:(struct CGRect)arg3 atIndex:(unsigned long long)arg4;
- (BOOL)textView:(NSTextView *)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
@end

@protocol XRPageBrowserDataSource
- (NSString *)titleForPageIndex:(unsigned long long)arg1;
- (void)willRemoveViewForPageIndex:(unsigned long long)arg1;
- (NSView *)viewForPageIndex:(unsigned long long)arg1;
- (unsigned long long)numberOfPages;
@end

@protocol XRUIStackFrame <NSCoding, NSObject>
- (long long)lineNumberForDisplay;
- (NSString *)pathForDisplay;
- (NSString *)symbolNameForUse;
- (NSString *)symbolNameForDisplay;
- (NSString *)libraryForDisplay;

@optional
- (BOOL)getWeight:(double *)arg1 at:(unsigned long long)arg2;
@end

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface PFTShortStringElement : PFTDataElement
{
}

- (id)createView;

@end

@interface PFTMultipleOptionsListElement : PFTDataElement
{
    NSMutableSet *_boundControls;
}

@property(retain, nonatomic) NSMutableSet *boundControls; // @synthesize boundControls=_boundControls;
- (void).cxx_destruct;
- (BOOL)acceptsFirstResponderInContent;
- (void)_updateChoice:(id)arg1;
- (id)menuItemGroup;
- (id)createView;
- (void)unbindTarget;

@end

@interface XRDataElementsStackView : NSStackView
{
}

+ (id)dataElementsStackView;

@end

@interface XREmbeddedScrollView : NSScrollView
{
}

- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

@interface XRLabledStringsListElement : PFTDataElement
{
}

- (id)createView;

@end

@interface PFTStackTraceElement : PFTDataElement <NSMenuDelegate, NSTableViewDataSource, NSTableViewDelegate>
{
    NSArray *_stacktrace;
    BOOL _topOfStackIsTruncated;
    NSMutableArray *_collapsedStacktrace;
    NSTableView *_tableView;
    struct _NSRange _filteringStackRange;
    NSFont *_normalFont;
    NSFont *_frameFont;
    BOOL _inverted;
    BOOL _calltreeOriginated;
    NSMutableArray *_releasePool;
    DVTGradientImageButton *_configurationButton;
}

+ (void)initialize;
@property(nonatomic) __weak DVTGradientImageButton *configurationButton; // @synthesize configurationButton=_configurationButton;
- (void).cxx_destruct;
- (id)stackFromTableView:(id)arg1;
- (id)tableView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 row:(long long)arg5 mouseLocation:(struct CGPoint)arg6;
- (BOOL)tableView:(id)arg1 shouldShowCellExpansionForTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 dataCellForTableColumn:(id)arg2 row:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)_symbolDoubleClicked:(id)arg1;
- (void)_selectionDidChange:(id)arg1;
- (void)_toggleCollapseLevel:(id)arg1;
- (void)setDocumentUUID:(id)arg1;
- (void)configureConfigurationButton:(id)arg1;
- (id)createView;
- (id)proxyWithFrame:(id)arg1;
- (id)stackTraceFromObjectValue;
- (void)noteSearchCriteria:(id)arg1;
- (BOOL)isSearchCriteriaReady;
- (id)tooltipForSearchCriteria;
- (id)searchCriteria;
- (BOOL)isSearchCriteria;
- (void)_copyFrames:(id)arg1;
- (void)_traceCall:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)downloadDSYM:(id)arg1;
- (void)symbolicateAddress:(id)arg1;
- (void)locateAndSymbolicateAddress:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)_handleAction:(id)arg1;
- (id)selectedObjects;
- (void)_refreshStack:(id)arg1;
- (id)_currentDocument;
- (void)_refreshDataSource;
- (void)_setConfigurationButtonState;
- (void)setup;
- (void)invert;
- (void)dealloc;
- (void)_invertStack:(id)arg1;
- (void)_displayFileIcon:(id)arg1;
- (void)_displayFilePath:(id)arg1;
- (void)_displayLibraries:(id)arg1;
- (void)_displayFrames:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface PFTStackTableView : NSTableView
{
}

- (struct CGSize)intrinsicContentSize;
- (void)copy:(id)arg1;

@end

@interface XRImageCell : NSImageCell
{
    NSColor *_bgColor;
    NSColor *_imageBGColor;
    BOOL _ignoreBackground;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)setDrawsBackground:(BOOL)arg1;
- (void)setImageBackgroundColor:(id)arg1;
- (void)setBackgroundColor:(id)arg1;
- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;

@end

@interface PFTSymbolTextFieldCell : XRVerticallyCenteredTextFieldCell
{
}

- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (void)drawWithExpansionFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)expansionFrameWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGSize)cellSize;

@end

@interface XRUIStackFrameProxy : NSObject
{
    id <XRUIStackFrame><NSObject> _stackFrame;
    NSFormatter *_weightFormatter;
}

- (void).cxx_destruct;
- (id)description;
- (id)stackFrame;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithStackFrame:(id)arg1 weightFormatter:(id)arg2;

@end

@interface PFTWeightedStackTraceElement : PFTStackTraceElement
{
    NSFormatter *_formatter;
}

- (void).cxx_destruct;
- (id)proxyWithFrame:(id)arg1;
- (id)stackTraceFromObjectValue;
- (id)createView;

@end

@interface XRResizingTextView : NSTextView
{
    BOOL _observingSuperFrameChanges;
}

- (void)_handleFrameChangedNotification:(id)arg1;
- (void)setUpConstriants;
- (void)sizeToFit;
- (struct CGSize)intrinsicContentSize;
- (void)didChangeText;
- (void)viewWillMoveToSuperview:(id)arg1;
- (void)awakeFromNib;
- (void)dealloc;

@end

@interface PFTCustomColorWell : NSColorWell
{
    NSGradient *_gradient;
}

- (void).cxx_destruct;
- (void)setColor:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)clicked:(id)arg1;

@end

@interface PFTColorWellsListElement : PFTDataElement
{
}

- (BOOL)acceptsFirstResponderInContent;
- (id)createView;

@end

@interface XRDataMiningDataElementViewController : NSViewController <NSTableViewDelegate, NSTableViewDataSource>
{
    NSMutableArray *_dataMiningRecords;
    BOOL _enabled;
    XRBacktraceRepository *_repository;
    XRCallTreeDetailView *_partnerDetailView;
    NSTableView *_table;
    NSTableColumn *_symbolColumn;
    NSTableColumn *_actionColumn;
    NSTableColumn *_enabledColumn;
    NSPopUpButtonCell *_cellPrototype;
    NSButton *_symbolButton;
    NSButton *_libraryButton;
    NSButton *_restoreButton;
}

@property(nonatomic) __weak NSButton *restoreButton; // @synthesize restoreButton=_restoreButton;
@property(nonatomic) __weak NSButton *libraryButton; // @synthesize libraryButton=_libraryButton;
@property(nonatomic) __weak NSButton *symbolButton; // @synthesize symbolButton=_symbolButton;
@property(nonatomic) __weak NSPopUpButtonCell *cellPrototype; // @synthesize cellPrototype=_cellPrototype;
@property(nonatomic) __weak NSTableColumn *enabledColumn; // @synthesize enabledColumn=_enabledColumn;
@property(nonatomic) __weak NSTableColumn *actionColumn; // @synthesize actionColumn=_actionColumn;
@property(nonatomic) __weak NSTableColumn *symbolColumn; // @synthesize symbolColumn=_symbolColumn;
@property(nonatomic) __weak NSTableView *table; // @synthesize table=_table;
@property(nonatomic) BOOL enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) XRCallTreeDetailView *partnerDetailView; // @synthesize partnerDetailView=_partnerDetailView;
@property(retain, nonatomic) XRBacktraceRepository *repository; // @synthesize repository=_repository;
- (void).cxx_destruct;
- (void)_reloadDataWithRecords:(id)arg1;
- (id)_unifyTraceWithRepositoryRecords:(id)arg1 additionList:(id)arg2 removalList:(id)arg3;
- (id)_dataMiningRecordsForSymbols:(id)arg1 treatAsLibrary:(BOOL)arg2 context:(id)arg3;
- (void)_applyRepositoryMiningContext:(id)arg1 toSymbolName:(id)arg2;
- (id)_selectedRecordsInExternalSelection:(BOOL)arg1;
- (id)_contextOptionsForContext:(id)arg1;
- (id)_dataCellForContext:(id)arg1;
- (id)_displayNameForContext:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 dataCellForTableColumn:(id)arg2 row:(long long)arg3;
- (void)tableView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)restore:(id)arg1;
- (void)filterLibraries:(id)arg1;
- (void)filterSymbols:(id)arg1;
- (void)_enableControls;
- (void)reloadData;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithCallTreeView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface PFTRadioButtonListElement : PFTDataElement
{
    XRDataElementsStackView *_viewer;
    NSMutableArray *_menuItems;
    long long _buttonIndex;
}

+ (void)initialize;
- (void).cxx_destruct;
- (BOOL)acceptsFirstResponderInContent;
- (void)_updateChoice:(id)arg1;
- (void)setButtonIndex:(long long)arg1;
- (long long)buttonIndex;
- (id)menuItemGroup;
- (id)view;
- (void)unbindTarget;
- (void)bindTarget:(id)arg1 toKeyPathArray:(id)arg2;

@end

@interface PFTImageViewer : NSImageView
{
}

- (void)setFrameSize:(struct CGSize)arg1;

@end

@interface PFTFileImageViewerElement : PFTDataElement
{
}

- (BOOL)dataViewCanResize;
- (BOOL)acceptsFirstResponderInContent;
- (id)createView;

@end

@interface PFTIntegerSpinnerElement : PFTDataElement
{
}

- (id)createView;

@end

@interface PFTStringPathControl : PFTPathControl
{
    NSMutableArray *_paths;
}

@property(retain, nonatomic) NSMutableArray *paths; // @synthesize paths=_paths;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface PFTPathElement : PFTDataElement
{
}

- (void)_pathControlClick:(id)arg1;
- (void)unbindTarget;
- (id)createView;

@end

@interface PFTViewElement : PFTDataElement
{
}

- (id)createView;
- (void)unbindTarget;

@end

@interface PFTLongStringElement : PFTDataElement
{
}

- (id)createView;

@end

@interface PFTPushButtonElement : PFTDataElement
{
}

- (id)createView;
- (void)_configureButtonAction:(id)arg1;

@end

@interface PFTAttributedStringElement : PFTDataElement
{
}

- (id)createView;

@end

@interface NSStringToNumberWithSubstitutionTransformer : NSValueTransformer
{
    NSDictionary *_swaps;
    NSString *_offString;
    NSString *_onString;
    long long _minVal;
    long long _maxVal;
    BOOL _active;
    unsigned short _etype;
    id _targetNotRetained;
    id _controlNotRetained;
    NSString *_keyPath;
}

+ (BOOL)allowsReverseTransformation;
+ (Class)transformedValueClass;
+ (id)transformerWithSubstitutions:(id)arg1 min:(id)arg2 max:(id)arg3 off:(id)arg4 target:(id)arg5 keyPath:(id)arg6 engineeringType:(unsigned short)arg7 active:(BOOL)arg8;
+ (void)saveState:(long long)arg1 forTarget:(id)arg2 keyPath:(id)arg3;
+ (long long)stateForTarget:(id)arg1 keyPath:(id)arg2;
- (void).cxx_destruct;
- (void)setActive:(BOOL)arg1;
- (BOOL)control:(id)arg1 textShouldEndEditing:(id)arg2;
- (void)setControl:(id)arg1;
- (id)unswappedString:(id)arg1;
- (id)swappedString:(id)arg1;
- (id)transformedValue:(id)arg1;
- (void)dealloc;
- (id)initWithSubstitutions:(id)arg1 min:(id)arg2 max:(id)arg3 off:(id)arg4 target:(id)arg5 keyPath:(id)arg6 engineeringType:(unsigned short)arg7 active:(BOOL)arg8;

@end

@interface PFTIntegerConstraintsList : PFTDataElement
{
    NSMutableArray *_transformers;
    NSTextField *_minValueField;
    NSTextField *_maxValueField;
}

- (void).cxx_destruct;
- (id)createView;
- (void)unbindTarget;

@end

@interface PFTStringsPopupList : PFTDataElement
{
}

- (id)createView;
- (void)unbindTarget;

@end

@interface XRGraphingElement : PFTDataElement
{
    NSMutableSet *_boundControls;
}

@property(retain, nonatomic) NSMutableSet *boundControls; // @synthesize boundControls=_boundControls;
- (void).cxx_destruct;
- (BOOL)acceptsFirstResponderInContent;
- (id)createView;
- (void)_imageMenuAction:(id)arg1;
- (void)unbindTarget;

@end

@interface XRAutomaticTimerDisplayElement : PFTDataElement
{
    NSMutableArray *_valueBoundFields;
}

- (void).cxx_destruct;
- (id)createView;
- (void)unbindTarget;

@end

@interface XRButtonWithAttributedStringResultElement : PFTDataElement
{
    NSTextView *_resultBox;
}

- (void).cxx_destruct;
- (id)createView;
- (id)attributedStringValue;
- (void)setAttributedStringValue:(id)arg1;
- (void)unbindTarget;

@end

@interface XRAutoresizingTextField : NSTextField <NSTextFieldDelegate>
{
}

- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)textDidChange:(id)arg1;
- (void)updatePreferredMaxLayoutWidth:(id)arg1;
- (struct CGSize)intrinsicContentSize;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface XRLegendColorWell : NSColorWell
{
}

- (BOOL)acceptsFirstResponder;
- (void)clicked:(id)arg1;

@end

@interface XRLegendTransparentButton : NSButton
{
}

- (BOOL)resignFirstResponder;
- (BOOL)acceptsFirstResponder;
- (void)mouseDown:(id)arg1;

@end

@interface XRGrowingTextField : NSTextField
{
    double _minWidth;
    double _maxLengthBuffer;
    NSString *_placeholder;
}

- (void).cxx_destruct;
- (void)setMaxLengthBuffer:(double)arg1;
- (BOOL)acceptsFirstResponder;
- (BOOL)becomeFirstResponder;
- (void)textDidEndEditing:(id)arg1;
- (void)textDidChange:(id)arg1;
- (void)sizeToFit;
- (void)resetToMaxSize;
- (void)resetToMinSize;
- (void)mouseDown:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 placeholderString:(id)arg2;

@end

@interface XRLegendElement : PFTDataElement
{
}

- (BOOL)acceptsFirstResponderInContent;
- (id)createView;
- (void)unbindTarget;

@end

@interface XRFocusTextView : XRResizingTextView <NSTextViewDelegate>
{
    NSString *_placeholderString;
    BOOL _hasPlaceholderString;
}

- (void).cxx_destruct;
- (void)textDidChange:(id)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)insertBacktab:(id)arg1;
- (void)changeColor:(id)arg1;
- (void)setString:(id)arg1;
- (void)doCommandBySelector:(SEL)arg1;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
- (id)initWithFrame:(struct CGRect)arg1 placeholderString:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface XRFocusScrollView : NSScrollView
{
}

- (void)viewDidMoveToSuperview;
- (void)awakeFromNib;
- (void)removeFocusRing:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface XRSummaryStringElement : PFTDataElement
{
}

- (id)createView;
- (void)unbindTarget;

@end

@interface XRDataMiningDataElement : PFTDataElement
{
    XRDataMiningDataElementViewController *_viewController;
}

@property(retain, nonatomic) XRDataMiningDataElementViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (id)createView;
- (void)unbindTarget;

@end

@interface XRPageBrowserElement : PFTDataElement <XRPageBrowserDataSource>
{
    XRPageBrowserViewController *_vc;
}

@property(retain) XRPageBrowserViewController *vc; // @synthesize vc=_vc;
- (void).cxx_destruct;
- (id)titleForPageIndex:(unsigned long long)arg1;
- (void)willRemoveViewForPageIndex:(unsigned long long)arg1;
- (id)viewForPageIndex:(unsigned long long)arg1;
- (unsigned long long)numberOfPages;
- (id)createView;
- (void)unbindTarget;

@end

@interface XRUnitChooserView : NSView
{
    NSTextField *_textField;
    NSPopUpButton *_popUpButton;
}

@property(readonly) NSPopUpButton *popUpButton; // @synthesize popUpButton=_popUpButton;
@property(readonly) NSTextField *textField; // @synthesize textField=_textField;
- (void).cxx_destruct;
- (void)setTextField:(id)arg1 popUpBox:(id)arg2;

@end

@interface XRUnitTransformer : NSValueTransformer
{
    int _conversionFactor;
}

+ (BOOL)allowsReverseTransformation;
+ (Class)transformedValueClass;
@property int conversionFactor; // @synthesize conversionFactor=_conversionFactor;
- (id)reverseTransformedValue:(id)arg1;
- (id)transformedValue:(id)arg1;

@end

@interface XRUnitChooserElement : PFTDataElement
{
    NSArray *_conversionFactors;
    NSValueTransformer *_transformer;
    NSNumberFormatter *_formatter;
}

- (void).cxx_destruct;
- (id)createView;
- (void)_popupSelected:(id)arg1;
- (void)unbindTarget;

@end

@interface PFTModalEditorButtonElement : PFTPushButtonElement
{
}

- (void)_configureButtonAction:(id)arg1;
- (void)_showModalEditor;

@end

@interface XRIconWithLabelsElement : PFTDataElement
{
}

+ (id)minorLabelAttributes;
+ (id)majorLabelAttributes;
- (id)createView;
- (void)unbindTarget;

@end

@interface XRPushButtonWithArrowsElement : PFTDataElement
{
}

- (void)_arrowClicked:(id)arg1;
- (id)createView;

@end

@interface XRFrameListTextFieldCell : XRVerticallyCenteredTextFieldCell
{
}

- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)titleRectForBounds:(struct CGRect)arg1;
- (void)drawWithExpansionFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGSize)cellSize;

@end

@interface XRFrameListElement : PFTDataElement <NSMenuDelegate, NSTableViewDataSource, NSTableViewDelegate>
{
    NSArray *_stacktrace;
    double _lineHeight;
    NSTableView *_tableNotRetained;
    struct _NSRange _filteringStackRange;
    NSFont *_normalFont;
    NSFont *_frameFont;
    BOOL _inverted;
    BOOL _calltreeOriginated;
    NSMutableArray *_releasePool;
}

+ (void)toggleDisplayFilePath;
+ (BOOL)displayFilePath;
+ (void)toggleDisplayFileIcon;
+ (BOOL)displayFileIcon;
+ (void)toggleDisplayFrames;
+ (BOOL)displayFrames;
+ (void)toggleDisplayLibraries;
+ (BOOL)displayLibraries;
+ (void)toggleInvertStack;
+ (BOOL)invertStack;
+ (id)colorForLibrary:(id)arg1;
- (void).cxx_destruct;
- (id)stackFromTableView:(id)arg1;
- (BOOL)tableView:(id)arg1 shouldShowCellExpansionForTableColumn:(id)arg2 row:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)_symbolDoubleClicked:(id)arg1;
- (void)_selectionDidChange:(id)arg1;
- (id)createView;
- (void)noteSearchCriteria:(id)arg1;
- (BOOL)isSearchCriteriaReady;
- (id)tooltipForSearchCriteria;
- (id)searchCriteria;
- (BOOL)isSearchCriteria;
- (void)_copyFrames:(id)arg1;
- (void)_traceCall:(id)arg1;
- (void)_displayFilePath:(id)arg1;
- (void)_displayFileIcon:(id)arg1;
- (void)_displayFrames:(id)arg1;
- (void)_displayLibraries:(id)arg1;
- (void)_colorLibraries:(id)arg1;
- (void)_invertStack:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (void)_handleAction:(id)arg1;
- (id)selectedObjects;
- (void)_refreshStack:(id)arg1;
- (void)setup;
- (void)invert;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface XRCommentsNavigatorElement : PFTDataElement <NSMenuDelegate, NSTableViewDataSource, NSTableViewDelegate>
{
    NSMutableArray *_comments;
    NSTableView *_tableNotRetained;
    struct _NSRange _filteringStackRange;
    NSFont *_normalFont;
    NSFont *_frameFont;
    BOOL _inverted;
}

+ (id)colorForLibrary:(id)arg1;
- (void).cxx_destruct;
- (id)stackFromTableView:(id)arg1;
- (BOOL)tableView:(id)arg1 shouldShowCellExpansionForTableColumn:(id)arg2 row:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)_selectionDidChange:(id)arg1;
- (void)_rowClicked:(id)arg1;
- (id)createView;
- (void)_copyFrames:(id)arg1;
- (BOOL)validateMenuItem:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;
- (id)selectedObjects;
- (void)setup;
- (void)invert;
- (void)_updateSortIcon;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface XRCountersSetupFormulaEditorCellView : NSTableCellView
{
    NSTextField *_nameCellView;
    NSTextField *_formulaTextField;
    DVTGradientImageButton *_cancelButton;
    DVTGradientImageButton *_acceptButton;
    NSPopUpButton *_insertFormulaMnemonicButton;
    NSMenu *_insertFormulaMnemonicButtonMenu;
    NSImageView *_warningImageView;
    NSTextField *_warningTextField;
}

@property(retain) NSTextField *warningTextField; // @synthesize warningTextField=_warningTextField;
@property(retain) NSImageView *warningImageView; // @synthesize warningImageView=_warningImageView;
@property(retain) NSMenu *insertFormulaMnemonicButtonMenu; // @synthesize insertFormulaMnemonicButtonMenu=_insertFormulaMnemonicButtonMenu;
@property(retain) NSPopUpButton *insertFormulaMnemonicButton; // @synthesize insertFormulaMnemonicButton=_insertFormulaMnemonicButton;
@property(retain) DVTGradientImageButton *acceptButton; // @synthesize acceptButton=_acceptButton;
@property(retain) DVTGradientImageButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain) NSTextField *formulaTextField; // @synthesize formulaTextField=_formulaTextField;
@property(retain) NSTextField *nameCellView; // @synthesize nameCellView=_nameCellView;
- (void).cxx_destruct;

@end

@interface XRCountersSetupViewController : NSViewController <NSTableViewDataSource, NSTableViewDelegate, NSTextFieldDelegate>
{
    NSStackView *_configStack;
    XRCountersSetupModel *_setupModel;
    XRTrace *_trace;
    DTKPCPU *_dtkpCPU;
    NSMutableDictionary *_cpuFormulaNamesToText;
    XRRecentArrayStoredPrefs *_recentCPUCounterEventAliasOrMnemonics;
    XRRecentArrayStoredPrefs *_recentCPUCountersFormulas;
    NSImage *_statusItemAddImage;
    NSImage *_statusItemDeleteImage;
    NSImage *_statusWarning;
    NSImage *_statusLightGreen;
    NSImage *_statusLightYellow;
    NSImage *_statusLightRed;
    XRCountersSetupEventOrFormula *_formulaBeingEdited;
    BOOL _formulaBeingEditedWasAlreadyInTable;
    NSString *_formulaNameBeingEdited;
    NSString *_formulaTextBeingEdited;
    NSString *_formulaWarningBeingEdited;
    BOOL _preventStateRecursion;
    BOOL _enablePMIElements;
    NSMutableArray *_counterNames;
    NSMutableArray *_counterNamesShort;
    NSTextField *_eventsText;
    NSView *_sampleByView;
    NSPopUpButton *_sampleByButton;
    NSView *_sampleRateView;
    NSTextField *_sampleRateTextField;
    NSView *_eventView;
    NSTextField *_eventLabel;
    NSPopUpButton *_eventButton;
    NSMenu *_eventButtonMenu;
    NSView *_callstacksView;
    NSView *_highFrequencyView;
    NSView *_cpuNameView;
    NSTextField *_cpuNameTextView;
    NSButton *_kernelCallstacksButton;
    NSButton *_highFrequencySamplingButton;
    DVTBorderedView *_graphAndButtonsView;
    DVTBorderedView *_buttonsView;
    NSTableView *_graphTable;
    DVTGradientImagePopUpButton *_addGraphButton;
    NSMenu *_addGraphButtonAddMenu;
    NSMenuItem *_addGraphButtonAddMenuItem;
    DVTGradientImageButton *_removeGraphButton;
    DVTGradientImagePopUpButton *_configureGraphButton;
    NSMenu *_configureGraphButtonMenu;
    NSMenuItem *_configureGraphButtonConfigureMenuItem;
    NSMenuItem *_configureGraphButtonCreateFormulaMenuItem;
    NSMenuItem *_configureGraphButtonRecentEntriesMenuItem;
    NSMenu *_configureGraphButtonModifyFormulaMenu;
    NSMenu *_configureGraphButtonDeleteFormulaMenu;
    NSMenu *_configureGraphButtonRecentEntriesMenu;
    NSMutableArray *_processorNames;
    NSMutableArray *_processorNamesOrig;
}

@property(nonatomic) BOOL enablePMIElements; // @synthesize enablePMIElements=_enablePMIElements;
@property(retain, nonatomic) NSMutableArray *processorNamesOrig; // @synthesize processorNamesOrig=_processorNamesOrig;
@property(retain, nonatomic) NSMutableArray *processorNames; // @synthesize processorNames=_processorNames;
@property(retain) NSMenu *configureGraphButtonRecentEntriesMenu; // @synthesize configureGraphButtonRecentEntriesMenu=_configureGraphButtonRecentEntriesMenu;
@property(retain) NSMenu *configureGraphButtonDeleteFormulaMenu; // @synthesize configureGraphButtonDeleteFormulaMenu=_configureGraphButtonDeleteFormulaMenu;
@property(retain) NSMenu *configureGraphButtonModifyFormulaMenu; // @synthesize configureGraphButtonModifyFormulaMenu=_configureGraphButtonModifyFormulaMenu;
@property(retain) NSMenuItem *configureGraphButtonRecentEntriesMenuItem; // @synthesize configureGraphButtonRecentEntriesMenuItem=_configureGraphButtonRecentEntriesMenuItem;
@property(retain) NSMenuItem *configureGraphButtonCreateFormulaMenuItem; // @synthesize configureGraphButtonCreateFormulaMenuItem=_configureGraphButtonCreateFormulaMenuItem;
@property(retain) NSMenuItem *configureGraphButtonConfigureMenuItem; // @synthesize configureGraphButtonConfigureMenuItem=_configureGraphButtonConfigureMenuItem;
@property NSMenu *configureGraphButtonMenu; // @synthesize configureGraphButtonMenu=_configureGraphButtonMenu;
@property DVTGradientImagePopUpButton *configureGraphButton; // @synthesize configureGraphButton=_configureGraphButton;
@property DVTGradientImageButton *removeGraphButton; // @synthesize removeGraphButton=_removeGraphButton;
@property NSMenuItem *addGraphButtonAddMenuItem; // @synthesize addGraphButtonAddMenuItem=_addGraphButtonAddMenuItem;
@property NSMenu *addGraphButtonAddMenu; // @synthesize addGraphButtonAddMenu=_addGraphButtonAddMenu;
@property DVTGradientImagePopUpButton *addGraphButton; // @synthesize addGraphButton=_addGraphButton;
@property NSTableView *graphTable; // @synthesize graphTable=_graphTable;
@property DVTBorderedView *buttonsView; // @synthesize buttonsView=_buttonsView;
@property DVTBorderedView *graphAndButtonsView; // @synthesize graphAndButtonsView=_graphAndButtonsView;
@property NSButton *highFrequencySamplingButton; // @synthesize highFrequencySamplingButton=_highFrequencySamplingButton;
@property NSButton *kernelCallstacksButton; // @synthesize kernelCallstacksButton=_kernelCallstacksButton;
@property NSTextField *cpuNameTextView; // @synthesize cpuNameTextView=_cpuNameTextView;
@property NSView *cpuNameView; // @synthesize cpuNameView=_cpuNameView;
@property NSView *highFrequencyView; // @synthesize highFrequencyView=_highFrequencyView;
@property NSView *callstacksView; // @synthesize callstacksView=_callstacksView;
@property NSMenu *eventButtonMenu; // @synthesize eventButtonMenu=_eventButtonMenu;
@property NSPopUpButton *eventButton; // @synthesize eventButton=_eventButton;
@property NSTextField *eventLabel; // @synthesize eventLabel=_eventLabel;
@property NSView *eventView; // @synthesize eventView=_eventView;
@property NSTextField *sampleRateTextField; // @synthesize sampleRateTextField=_sampleRateTextField;
@property NSView *sampleRateView; // @synthesize sampleRateView=_sampleRateView;
@property NSPopUpButton *sampleByButton; // @synthesize sampleByButton=_sampleByButton;
@property NSView *sampleByView; // @synthesize sampleByView=_sampleByView;
@property(retain) NSTextField *eventsText; // @synthesize eventsText=_eventsText;
@property(retain, nonatomic) NSMutableArray *counterNamesShort; // @synthesize counterNamesShort=_counterNamesShort;
@property(retain, nonatomic) NSMutableArray *counterNames; // @synthesize counterNames=_counterNames;
@property(retain, nonatomic) XRCountersSetupModel *setupModel; // @synthesize setupModel=_setupModel;
- (void).cxx_destruct;
- (void)_tableDoubleClicked:(id)arg1;
- (BOOL)_validateEventsAndFormulas;
- (void)tableViewSelectionIsChanging:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (void)_addMnemonicToFormulaMenuItemChosen:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)_instrumentStateChanged:(id)arg1;
- (void)cancelNewFormulaClicked:(id)arg1;
- (void)acceptNewFormulaClicked:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)recentEntriesClicked:(id)arg1;
- (void)_setupConfigureEventOrFormulaMenu;
- (void)_deleteFormulaMenuItemChosen:(id)arg1;
- (void)_modifyFormulaMenuItemChosen:(id)arg1;
- (void)_addFormulaMenuItemChosen:(id)arg1;
- (void)_addEventMenuItemChosen:(id)arg1;
- (void)createFormulaClicked:(id)arg1;
- (void)_setupAddEventOrFormulaMenu;
- (void)_pmiEventMenuItemChosen:(id)arg1;
- (void)_addRecentFormulaName:(id)arg1;
- (void)_addRecentEventAliasOrMnemonic:(id)arg1;
- (void)_setupEventMenu;
- (void)setPmiEvent:(id)arg1;
- (void)removeEventOrFormula:(id)arg1;
- (void)highFrequencySamplingChanged:(id)arg1;
- (void)callstacksChanged:(id)arg1;
- (void)sampleRateChanged:(id)arg1;
- (void)sampleByChanged:(id)arg1;
- (void)_sampleRateLayoutShowEvents:(BOOL)arg1;
- (void)_updateUIEnabledState;
- (BOOL)hasPMDevice;
- (void)dealloc;
- (id)initWithModel:(id)arg1 trace:(id)arg2 cpuFormulaNamesToText:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface XRCountersSetupElement : PFTDataElement
{
    XRCountersSetupViewController *_viewController;
}

- (void).cxx_destruct;
- (id)createView;
- (void)unbindTarget;

@end

@interface XRStringInputWithLabelView : NSView
{
    NSTextField *_textField;
    NSTextField *_labelField;
}

@property(readonly, nonatomic) NSTextField *labelField; // @synthesize labelField=_labelField;
@property(readonly, nonatomic) NSTextField *textField; // @synthesize textField=_textField;
- (void).cxx_destruct;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setTextField:(id)arg1 labelField:(id)arg2;

@end

@interface XRStringInputWithLabelElement : PFTDataElement
{
}

- (id)createView;

@end

#endif /* DataElementsPlugin_xrplugin_h */
