//
//  DTLLVMBinaryAnalysisPlugin.xrplugin.h
//  MacDemo
//
//  Created by szzc on 2016/11/25.
//  Copyright © 2016年 szzc. All rights reserved.
//

#ifndef DTLLVMBinaryAnalysisPlugin_xrplugin_h
#define DTLLVMBinaryAnalysisPlugin_xrplugin_h
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct NSObject {
    Class _field1;
};

struct _CSTypeRef {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned long long _field1;
    id *_field2;
    unsigned long long *_field3;
    unsigned long long _field4[5];
} CDStruct_70511ce9;

#pragma mark Typedef'd Unions

typedef union {
    struct {
        unsigned int level:29;
        unsigned int bflag:1;
        unsigned int eflag:1;
    } depth;
    unsigned int value;
} CDUnion_dda718c0;

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/DTLLVMBinaryAnalysisPlugin.xrplugin/Contents/MacOS/DTLLVMBinaryAnalysisPlugin
// UUID: D45A4240-8642-316E-933E-37D3A7FB9C33
//
//                           Arch: x86_64
//                 Source version: 61529.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.12.0
//
// Objective-C Garbage Collection: Unsupported
//

@protocol NSFastEnumeration
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
@end

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(Protocol *)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (BOOL)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol XRCodeLineProtocol
@property(readonly, nonatomic) unsigned long long length;
@property(readonly, nonatomic) unsigned long long byteOffset;
@property(readonly, nonatomic) NSString *lineString;

@optional
- (NSString *)timingString;
- (unsigned long long)lineNumber;
- (NSString *)locationReference;
- (unsigned long long)absoluteAddress;
- (NSAttributedString *)attributedLineString;
@end

@protocol XRDisassembledInstructionsProtocol <NSFastEnumeration>
- (NSData *)binaryData;
- (unsigned long long)cpuMode;
- (int)cpuSubType;
- (int)cpuType;
- (BOOL)getSourceLine:(id *)arg1 atIndex:(unsigned long long)arg2 error:(id *)arg3;

@optional
- (NSArray *)staticAnalysis;
- (BOOL)disassemblyCompleted;
@end

@protocol XRDisassemblerProtocol <NSObject>
- (BOOL)detectAsmLoopsIn:(struct NSObject *)arg1 error:(id *)arg2;
- (BOOL)fixupCallstack:(unsigned long long *)arg1 frameCount:(unsigned int *)arg2 extraRegisters:(unsigned int)arg3 withSymbolicator:(struct _CSTypeRef)arg4 hasKernelFrames:(BOOL)arg5;
- (struct NSObject *)instructionsForBinary:(NSData *)arg1 andAddress:(unsigned long long)arg2 withCPUType:(int)arg3 andSubtype:(int)arg4 andMode:(unsigned long long)arg5 error:(id *)arg6;
@end

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface XRLLVMDisassemblerPlugin : NSObject <XRDisassemblerProtocol>
{
}

- (BOOL)detectAsmLoopsIn:(struct NSObject *)arg1 error:(id *)arg2;
- (BOOL)fixupCallstack:(unsigned long long *)arg1 frameCount:(unsigned int *)arg2 extraRegisters:(unsigned int)arg3 withSymbolicator:(struct _CSTypeRef)arg4 hasKernelFrames:(BOOL)arg5;
- (struct NSObject *)instructionsForBinary:(id)arg1 andAddress:(unsigned long long)arg2 withCPUType:(int)arg3 andSubtype:(int)arg4 andMode:(unsigned long long)arg5 error:(id *)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface XRLLVMInstruction : NSObject <XRCodeLineProtocol>
{
    unsigned long long _byteOffset;
    unsigned long long _instLength;
    NSMutableArray *_targetOffsets;
    NSMutableAttributedString *_attrLine;
    CDUnion_dda718c0 _loopDepth;
    long long _jumpDistance;
    const char *_mnemonicString;
    const char *_operandsString;
}

@property(nonatomic) const char *operandsString; // @synthesize operandsString=_operandsString;
@property(nonatomic) const char *mnemonicString; // @synthesize mnemonicString=_mnemonicString;
@property(nonatomic) CDUnion_dda718c0 loopDepth; // @synthesize loopDepth=_loopDepth;
@property(nonatomic) long long jumpDistance; // @synthesize jumpDistance=_jumpDistance;
- (void).cxx_destruct;
- (BOOL)endOfLoop;
- (BOOL)startOfLoop;
- (int)loopIndent;
@property(readonly, nonatomic) unsigned long long length;
- (void)setByteOffset:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long byteOffset;
- (id)attributedLineString;
@property(readonly, nonatomic) NSString *lineString;
- (id)attributedStringFromOperands;
- (void)markPlaceholders:(id)arg1 inString:(id)arg2 withArrayEntries:(id)arg3 usingBlock:(CDUnknownBlockType)arg4;
- (void)addTargetAbsoluteAddress:(long long)arg1;
- (void)addTargetOffset:(long long)arg1;
- (void)setInstLength:(unsigned long long)arg1;
- (void)dealloc;
- (id)init;

@end

@interface XRLLVMDisassembledInstructions : NSObject <XRDisassembledInstructionsProtocol>
{
    NSData *_bytes;
    BOOL _disasmComplete;
    BOOL _loopsDetected;
    void *_disasmContext;
    unsigned long long _loadAddr;
    XRLLVMInstruction *_current_inst;
    NSMutableArray *_llvmInstArray;
    int _cpuType;
    int _cpuSubType;
    unsigned long long _cpuMode;
    int _instructionSkipLength;
}

- (void).cxx_destruct;
- (BOOL)getSourceLine:(id *)arg1 atIndex:(unsigned long long)arg2 error:(id *)arg3;
- (BOOL)detectAsmCodeLoops;
- (void)performDisassembly;
- (unsigned long long)baseOffset;
- (unsigned long long)decodedCount;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)binaryData;
- (unsigned long long)cpuMode;
- (int)cpuSubType;
- (int)cpuType;
- (unsigned long long)offsetOfInstructionAtIndex:(unsigned long long)arg1;
- (const char *)symbolicateReferenceToAddress:(unsigned long long)arg1 withTypePtr:(unsigned long long *)arg2 withPC:(unsigned long long)arg3 withNamePtr:(const char **)arg4;
- (void)dealloc;
- (id)initWithBinary:(id)arg1 andAddress:(unsigned long long)arg2 forCPUType:(int)arg3 andSubtype:(int)arg4 andMode:(unsigned long long)arg5;

@end

#endif /* DTLLVMBinaryAnalysisPlugin_xrplugin_h */
