//
//  ProductionPlugin.xrplugin.h
//  MacDemo
//
//  Created by szzc on 2016/11/25.
//  Copyright © 2016年 szzc. All rights reserved.
//

#ifndef ProductionPlugin_xrplugin_h
#define ProductionPlugin_xrplugin_h

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/ProductionPlugin.xrplugin/Contents/MacOS/ProductionPlugin
// UUID: B480A84F-5817-3CE2-B2F3-FD90F2B240AC
//
//                           Arch: x86_64
//                 Source version: 61529.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.12.0
//

//
// This file does not contain any Objective-C runtime information.
//

#endif /* ProductionPlugin_xrplugin_h */
