//
//  StandardAppUI.xrappui.h
//  MacDemo
//
//  Created by szzc on 2016/11/25.
//  Copyright © 2016年 szzc. All rights reserved.
//

#ifndef StandardAppUI_xrappui_h
#define StandardAppUI_xrappui_h
//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/StandardAppUI.xrappui/Contents/MacOS/StandardAppUI
// UUID: F65ECDC2-71F3-3B43-A466-1F79143C7A2B
//
//                           Arch: x86_64
//                 Source version: 61529.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.12.0
//

//
// This file does not contain any Objective-C runtime information.
//

#endif /* StandardAppUI_xrappui_h */
