//
//  XRQuartzPlugin.xrplugin.h
//  MacDemo
//
//  Created by szzc on 2016/11/25.
//  Copyright © 2016年 szzc. All rights reserved.
//

#ifndef XRQuartzPlugin_xrplugin_h
#define XRQuartzPlugin_xrplugin_h

//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct XRTimeRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark -

//
// File: /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/PlugIns/XRQuartzPlugin.xrplugin/Contents/MacOS/XRQuartzPlugin
// UUID: 71777D36-9184-3EAE-8A98-6723834E66BE
//
//                           Arch: x86_64
//                 Source version: 61529.0.0.0.0
//       Minimum Mac OS X version: 10.10.0
//                    SDK version: 10.12.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @loader_path/../../../../Frameworks
//                               = /Applications/Xcode.app/Contents/Applications/Instruments.app/Contents/Frameworks
//                       Run path: @loader_path/../../../../../../../../SharedFrameworks
//                               = /Applications/Xcode.app/SharedFrameworks
//

@protocol NSObject
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;
@property(readonly) unsigned long long hash;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (BOOL)respondsToSelector:(SEL)arg1;
- (BOOL)conformsToProtocol:(Protocol *)arg1;
- (BOOL)isMemberOfClass:(Class)arg1;
- (BOOL)isKindOfClass:(Class)arg1;
- (BOOL)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
- (BOOL)isEqual:(id)arg1;

@optional
@property(readonly, copy) NSString *debugDescription;
@end

@protocol NSTableViewDataSource <NSObject>

@optional
- (NSArray *)tableView:(NSTableView *)arg1 namesOfPromisedFilesDroppedAtDestination:(NSURL *)arg2 forDraggedRowsWithIndexes:(NSIndexSet *)arg3;
- (BOOL)tableView:(NSTableView *)arg1 acceptDrop:(id <NSDraggingInfo>)arg2 row:(long long)arg3 dropOperation:(unsigned long long)arg4;
- (unsigned long long)tableView:(NSTableView *)arg1 validateDrop:(id <NSDraggingInfo>)arg2 proposedRow:(long long)arg3 proposedDropOperation:(unsigned long long)arg4;
- (BOOL)tableView:(NSTableView *)arg1 writeRowsWithIndexes:(NSIndexSet *)arg2 toPasteboard:(NSPasteboard *)arg3;
- (void)tableView:(NSTableView *)arg1 updateDraggingItemsForDrag:(id <NSDraggingInfo>)arg2;
- (void)tableView:(NSTableView *)arg1 draggingSession:(NSDraggingSession *)arg2 endedAtPoint:(struct CGPoint)arg3 operation:(unsigned long long)arg4;
- (void)tableView:(NSTableView *)arg1 draggingSession:(NSDraggingSession *)arg2 willBeginAtPoint:(struct CGPoint)arg3 forRowIndexes:(NSIndexSet *)arg4;
- (id <NSPasteboardWriting>)tableView:(NSTableView *)arg1 pasteboardWriterForRow:(long long)arg2;
- (void)tableView:(NSTableView *)arg1 sortDescriptorsDidChange:(NSArray *)arg2;
- (void)tableView:(NSTableView *)arg1 setObjectValue:(id)arg2 forTableColumn:(NSTableColumn *)arg3 row:(long long)arg4;
- (id)tableView:(NSTableView *)arg1 objectValueForTableColumn:(NSTableColumn *)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(NSTableView *)arg1;
@end

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
@end

@protocol __ARCLiteKeyedSubscripting__
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
@end

@interface XRVideoCardInstrumentDecoratorInterval : DTTimelineDecorator
{
    XRVideoCardRun *_run;
    unsigned long long _graphIndex;
}

- (void).cxx_destruct;
- (id)decorateInspectionRanges:(id)arg1;
- (BOOL)mustDecorateOnMainThread;
- (id)decorateContainer:(struct DTTimelineDecorationContainer *)arg1;
- (void)setDefaultsForPlane:(id)arg1;
- (id)initWithRun:(id)arg1 graphIndex:(unsigned long long)arg2;
- (id)init;

@end

@interface XRVideoCardInstrument : XRLegacyInstrument <NSTableViewDataSource>
{
    NSThread *_dataCollectionThread;
    BOOL _doCollectData;
    long long _samplingRate;
    long long _incomingDataCount;
    long long _dataCountAccountedFor;
    unsigned long long _lastRefresh;
    unsigned long long _baselineTime;
    NSTimer *_refreshTimer;
    NSMutableArray *_driverNames;
    NSMutableArray *_availableStatistics;
    NSMutableArray *_availableStatisticsTransformed;
    PFTTableDetailView *_detailView;
    BOOL _detailViewInverted;
    NSMutableArray *_driverFilters;
    NSString *_selectedDriver;
    XRDevice *_lastTargetDevice;
    DTXChannel *_channel;
    NSLock *_serviceQueueLock;
    NSArray *_enabledStatsInTemplate;
    NSMutableDictionary *_statisticsToDisplay;
    NSMutableArray *_statisticsToDisplayOrder;
}

@property(retain, nonatomic) NSMutableArray *statisticsToDisplayOrder; // @synthesize statisticsToDisplayOrder=_statisticsToDisplayOrder;
@property(retain, nonatomic) NSMutableDictionary *statisticsToDisplay; // @synthesize statisticsToDisplay=_statisticsToDisplay;
@property(retain, nonatomic) NSArray *enabledStatsInTemplate; // @synthesize enabledStatsInTemplate=_enabledStatsInTemplate;
- (void).cxx_destruct;
- (void)_mainThreadAddSample:(id)arg1;
- (void)_collectDataForRun:(id)arg1;
- (void)trackFocusedOnEventAtUnfilteredIndex:(unsigned long long)arg1;
- (void)trackFocusedOnEventAtTime:(unsigned long long)arg1;
- (id)translateSystemValue:(id)arg1 forStatistic:(id)arg2;
- (id)tableColumnDescriptorsForTable:(id)arg1;
- (void)configureTrack:(id)arg1;
- (id)dataSourceForBrushWithName:(id)arg1;
- (id)_fixupLoadedBrushName:(id)arg1;
- (void)stopRecording;
- (void)startRecording;
- (BOOL)verifyEnvironment:(id)arg1 arguments:(id)arg2 instruments:(id)arg3 error:(id *)arg4;
- (BOOL)configureEnvironment:(id)arg1 arguments:(id)arg2 instruments:(id)arg3 error:(id *)arg4;
- (void)setSelectedTimeRange:(struct XRTimeRange)arg1;
- (void)_noteNewDataInDetailView:(id)arg1;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (long long)samplingRate;
- (void)setSamplingRate:(long long)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)dataElementsForContext:(id)arg1;
- (id)detailElementsForExtendedDetailViewContext;
- (id)detailElementsForDetailViewContext;
- (void)selectionDidChange:(id)arg1;
- (void)singleClick:(id)arg1;
- (id)_detailView;
- (id)detailElementsForConfigurationViewContext;
- (id)detailElementsForSetupViewContext;
- (BOOL)initialValueForSwitch:(id)arg1;
- (void)freeSwitchAttributes;
- (void)initializeSwitchAttributes;
- (void)_dropChannel:(id)arg1;
- (id)channel;
- (id)configurationDataElementsForInspector:(id)arg1;
- (BOOL)willProvideConfigurationDataElementsForInspector:(id)arg1;
- (void)resetTargetDeviceProperties;
- (void)setTargetType:(int)arg1;
- (id)enabledStatisticNameAtIndex:(unsigned long long)arg1;
- (void)gatherCollectableStatistics;
- (void)setSelectedDriver:(id)arg1;
- (id)selectedDriver;
- (void)unobserveStatistics;
- (id)availableStatisticsTransformed;
- (id)driverNames;
- (id)availableStatistics;
- (void)queryCards;
- (void)setNeedsTrackRefresh;
- (void)setTrace:(id)arg1;
- (void)dealloc;
- (id)initWithExtension:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

@interface XRVideoCardRun : XRRun
{
    NSArray *_availableStatistics;
    NSArray *_driverNames;
    NSArray *_availableStatisticsTransformed;
    NSMutableArray *_data;
    NSArrayController *_controller;
    NSLock *_dataLock;
    unsigned long long _baselineTime;
}

+ (unsigned long long)timeOfSample:(id)arg1;
+ (void)initialize;
@property(nonatomic) unsigned long long baselineTime; // @synthesize baselineTime=_baselineTime;
@property(retain, nonatomic) NSArray *availableStatisticsTransformed; // @synthesize availableStatisticsTransformed=_availableStatisticsTransformed;
@property(retain, nonatomic) NSArray *driverNames; // @synthesize driverNames=_driverNames;
@property(retain, nonatomic) NSArray *availableStatistics; // @synthesize availableStatistics=_availableStatistics;
- (void).cxx_destruct;
- (void)setSelectedTimeRange:(struct XRTimeRange)arg1 forDriver:(id)arg2;
- (id)samplesIntersectingRange:(struct XRTimeRange)arg1 expandedBeginningOut:(char *)arg2;
- (id)samplesInRange:(struct XRTimeRange)arg1 filtered:(BOOL)arg2;
- (unsigned long long)indexOfSample:(id)arg1 filtered:(BOOL)arg2;
- (id)sampleAtIndex:(unsigned long long)arg1 filtered:(BOOL)arg2;
- (id)valueForStatistic:(id)arg1 atIndex:(unsigned long long)arg2 filtered:(BOOL)arg3;
- (unsigned long long)numberOfSamples:(BOOL)arg1;
- (void)addDataSample:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

#endif /* XRQuartzPlugin_xrplugin_h */
